import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BrowsingSection, NavigationBar, SearchBar } from "@/components";
import { navItems } from "../components/constants";
import { test_products } from "../components/testData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='font-serif'>
        <div className="h-60 bg-[url('/assets/banner-3.png')] bg-no-repeat bg-cover bg-center"></div>
        <header className='flex px-10 py-10'>
          <div className='w-1/3'>My Garden world</div>
          <SearchBar />
        </header>
        <nav className='border-dotted border-y-2 border-emerald-900'>
          <NavigationBar allNavItems={navItems} />
        </nav>

        {children}
      </body>
    </html>
  );
}
