import { ProductItem } from "../constants";

export const test_products: ProductItem[] = [
  {
    name: "bok-choi-jade-star",
    label: "Bok Choi Jade Star",
    image: "/assets/Bok-Choi-Jade-star.jpg",
    price: 2490,
    shortDescription: "",
    categories: ["Leafy Greens", "Cold Weather", "Easy"],
    sku: "A083",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 110
  },
  {
    name: "bok-choi-dark-green",
    label: "Bok Choi Dark Green",
    image: "/assets/Bok-Choi-Dark-Green.jpg",
    price: 1990,
    shortDescription: "",
    categories: ["Leafy Greens", "Cool Weather", "Easy"],
    sku: "A073",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 149
  },
  {
    name: "tong-ho-crispy-stem",
    label: "Tongho Crispy Stem",
    image: "/assets/Tongho-Crispy-Stem.jpg",
    price: 1990,
    shortDescription: "",
    categories: ["Leafy Greens", "Cold Weather", "Easy"],
    sku: "A051",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 73
  },
  {
    name: "tong-ho-serrated-leaf",
    label: "Tongho Serrated Leaf",
    image: "/assets/Tongho-Serrated-Leaf.jpg",
    price: 1990,
    shortDescription: "",
    categories: ["Leafy Greens", "Cold Weather", "Easy"],
    sku: "A050",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 56
  },
  {
    name: "bok-choi-jade-star",
    label: "Bok Choi Jade Star",
    image: "/assets/Bok-Choi-Jade-star.jpg",
    price: 2490,
    shortDescription: "",
    categories: ["Leafy Greens", "Cold Weather", "Easy"],
    sku: "A083",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 110
  },
  {
    name: "bok-choi-dark-green",
    label: "Bok Choi Dark Green",
    image: "/assets/Bok-Choi-Dark-Green.jpg",
    price: 1990,
    shortDescription: "",
    categories: ["Leafy Greens", "Cool Weather", "Easy"],
    sku: "A073",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 149
  },
  {
    name: "tong-ho-crispy-stem",
    label: "Tongho Crispy Stem",
    image: "/assets/Tongho-Crispy-Stem.jpg",
    price: 1990,
    shortDescription: "",
    categories: ["Leafy Greens", "Cold Weather", "Easy"],
    sku: "A051",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 73
  },
  {
    name: "tong-ho-serrated-leaf",
    label: "Tongho Serrated Leaf",
    image: "/assets/Tongho-Serrated-Leaf.jpg",
    price: 1990,
    shortDescription: "",
    categories: ["Leafy Greens", "Cold Weather", "Easy"],
    sku: "A050",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 56
  },
  {
    name: "bok-choi-jade-star",
    label: "Bok Choi Jade Star",
    image: "/assets/Bok-Choi-Jade-star.jpg",
    price: 2490,
    shortDescription: "",
    categories: ["Leafy Greens", "Cold Weather", "Easy"],
    sku: "A083",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 110
  },
  {
    name: "bok-choi-dark-green",
    label: "Bok Choi Dark Green",
    image: "/assets/Bok-Choi-Dark-Green.jpg",
    price: 1990,
    shortDescription: "",
    categories: ["Leafy Greens", "Cool Weather", "Easy"],
    sku: "A073",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 149
  },
  {
    name: "tong-ho-crispy-stem",
    label: "Tongho Crispy Stem",
    image: "/assets/Tongho-Crispy-Stem.jpg",
    price: 1990,
    shortDescription: "",
    categories: ["Leafy Greens", "Cold Weather", "Easy"],
    sku: "A051",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 73
  },
  {
    name: "tong-ho-serrated-leaf",
    label: "Tongho Serrated Leaf",
    image: "/assets/Tongho-Serrated-Leaf.jpg",
    price: 1990,
    shortDescription: "",
    categories: ["Leafy Greens", "Cold Weather", "Easy"],
    sku: "A050",
    description: "",
    additionalInfo: "",
    plantingGuild: "",
    stockAmount: 56
  }
];
